title: MCP Security Research
description: Security Research on AI, Agents, and MCP Implementations
author: Evan Harris
url: "https://mcpsec.dev"
baseurl: ""

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Header navigation
header_pages:
  - about.md
  - advisories/index.html

# Markdown settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /blog/:year/:month/:title/

# Collections for different content types
collections:
  advisories:
    output: true
    permalink: /advisories/:name/

# SEO and social media
twitter:
  username: Evan__Harris
  card: summary_large_image

# Defaults for pages
defaults:
  - scope:
      path: ""
    values:
      image: /assets/og-image.png
  - scope:
      path: "AGENTS.md"
    values:
      sitemap: false
  - scope:
      path: "DEVELOPMENT.md"
    values:
      sitemap: false
  - scope:
      path: "SECURITY.md"
    values:
      sitemap: false