title: MCP Security Research
description: Security Research on AI, Agents, and MCP Implementations
author: Evan Harris
url: "https://mcpsec.dev"
baseurl: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /blog/:year/:month/:title/

# Collections for different content types
collections:
  advisories:
    output: true
    permalink: /advisories/:name/