name: Generate OG Images

on:
  push:
    branches:
      - master
    paths:
      - '_advisories/**'
      - '_templates/og-image.html'
      - 'scripts/generate-og-images.js'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate OG images
        run: npm run generate-og

      - name: Commit generated images
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/og/*.png
          git diff --staged --quiet || git commit -m "Generate OG images for advisories [skip ci]"
          git push
